name: dsnd-proj5
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.2
    - pip
    - pip:
        - numpy
        - matplotlib
        - jupyter
        - pandas
        - scikit-learn
        - plotly
        - statsmodels
        - seaborn
